//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_VolleyballClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active_Players
    {
        public string surname_player { get; set; }
        public string name_player { get; set; }
    }
}
