//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_VolleyballClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coach_Contact_Info
    {
        public byte coach_ID { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string street_number { get; set; }
        public string postal_code { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
    
        public virtual Coach Coach { get; set; }
    }
}
