//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_VolleyballClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guardian
    {
        public int guardian_ID { get; set; }
        public string guardian_surname { get; set; }
        public string guardian_name { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public long player_ID { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
