//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_VolleyballClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.Guardians = new HashSet<Guardian>();
            this.Payments = new HashSet<Payment>();
            this.Team_members = new HashSet<Team_members>();
        }
    
        public long player_ID { get; set; }
        public string surname_player { get; set; }
        public string name_player { get; set; }
        public System.DateTime birthday_date { get; set; }
        public string club_card_number { get; set; }
        public string license_number { get; set; }
        public Nullable<System.DateTime> validity_license { get; set; }
        public Nullable<System.DateTime> validity_medical_ex { get; set; }
        public string on_lending { get; set; }
        public string native { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guardian> Guardians { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Player_Contact_Info Player_Contact_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team_members> Team_members { get; set; }
    }
}
